import { TimetableEntry, Day } from './types';

const subjects = [
  { name: 'Intro to AI', color: 'border-purple-500 bg-purple-50' },
  { name: 'Data Structures', color: 'border-yellow-500 bg-yellow-50' },
  { name: 'Algorithms', color: 'border-green-500 bg-green-50' },
  { name: 'Web Development', color: 'border-pink-500 bg-pink-50' },
  { name: 'Database Systems', color: 'border-red-500 bg-red-50' },
  { name: 'Operating Systems', color: 'border-blue-500 bg-blue-50' },
  { name: 'Linear Algebra', color: 'border-indigo-500 bg-indigo-50' },
  { name: 'Calculus II', color: 'border-gray-500 bg-gray-50' },
  { name: 'Physics I', color: 'border-orange-500 bg-orange-50' },
];

const faculties = ['Dr. Smith', 'Prof. Jones', 'Dr. Lee', 'Prof. Davis', 'Dr. Patel'];
const rooms = ['A101', 'B202', 'C303', 'Lab-1', 'Lab-2'];
const days: Day[] = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'];

export const mockTimetable: TimetableEntry[] = [
  {
    id: '1',
    dayOfWeek: 'Monday',
    startTime: '09:00',
    endTime: '11:00',
    subject: 'Intro to AI',
    faculty: 'Dr. Smith',
    room: 'A101',
    classId: 'CS301',
    color: subjects[0].color,
    eventType: 'in-person',
  },
  {
    id: '2',
    dayOfWeek: 'Monday',
    startTime: '11:00',
    endTime: '12:00',
    subject: 'Data Structures',
    faculty: 'Prof. Jones',
    room: 'B202',
    classId: 'CS201',
    color: subjects[1].color,
     eventType: 'in-person',
  },
  {
    id: '3',
    dayOfWeek: 'Monday',
    startTime: '14:00',
    endTime: '16:00',
    subject: 'Web Development',
    faculty: 'Dr. Lee',
    room: 'Lab-1',
    classId: 'CS405',
    color: subjects[3].color,
    eventType: 'online',
  },
  {
    id: '4',
    dayOfWeek: 'Tuesday',
    startTime: '10:00',
    endTime: '12:00',
    subject: 'Algorithms',
    faculty: 'Dr. Patel',
    room: 'C303',
    classId: 'CS302',
    color: subjects[2].color,
     eventType: 'in-person',
  },
  {
    id: '5',
    dayOfWeek: 'Tuesday',
    startTime: '13:00',
    endTime: '15:00',
    subject: 'Database Systems',
    faculty: 'Prof. Jones',
    room: 'Lab-2',
    classId: 'CS305',
    color: subjects[4].color,
    eventType: 'online',
  },
  {
    id: '6',
    dayOfWeek: 'Wednesday',
    startTime: '09:00',
    endTime: '10:00',
    subject: 'Data Structures',
    faculty: 'Prof. Jones',
    room: 'B202',
    classId: 'CS201',
    color: subjects[1].color,
     eventType: 'in-person',
  },
  {
    id: '7',
    dayOfWeek: 'Wednesday',
    startTime: '10:00',
    endTime: '12:00',
    subject: 'Operating Systems',
    faculty: 'Dr. Smith',
    room: 'A101',
    classId: 'CS401',
    color: subjects[5].color,
    eventType: 'in-person',
  },
  {
    id: '8',
    dayOfWeek: 'Wednesday',
    startTime: '15:00',
    endTime: '17:00',
    subject: 'Club Activity',
    faculty: 'N/A',
    room: 'Auditorium',
    classId: 'EXTRA',
    color: 'border-gray-500 bg-gray-100',
    eventType: 'in-person',
  },
   {
    id: '9',
    dayOfWeek: 'Thursday',
    startTime: '11:00',
    endTime: '13:00',
    subject: 'Calculus II',
    faculty: 'Dr. Evans',
    room: 'D401',
    classId: 'MA202',
    color: subjects[7].color,
    eventType: 'in-person',
  },
  {
    id: '10',
    dayOfWeek: 'Thursday',
    startTime: '14:00',
    endTime: '16:00',
    subject: 'Physics I',
    faculty: 'Dr. Green',
    room: 'PHY-Lab',
    classId: 'PHY101',
    color: subjects[8].color,
    eventType: 'in-person',
  },
  {
    id: '11',
    dayOfWeek: 'Friday',
    startTime: '09:00',
    endTime: '11:00',
    subject: 'Algorithms',
    faculty: 'Dr. Patel',
    room: 'C303',
    classId: 'CS302',
    color: subjects[2].color,
    eventType: 'online',
  },
  {
    id: '12',
    dayOfWeek: 'Friday',
    startTime: '13:00',
    endTime: '14:00',
    subject: 'Linear Algebra',
    faculty: 'Dr. Evans',
    room: 'D401',
    classId: 'MA203',
    color: subjects[6].color,
     eventType: 'in-person',
  },
];
