import { TimetableEntry, Day } from './types';

const subjects = [
  { name: 'Intro to AI', color: 'bg-blue-200 text-blue-800 border-blue-300' },
  { name: 'Data Structures', color: 'bg-green-200 text-green-800 border-green-300' },
  { name: 'Algorithms', color: 'bg-purple-200 text-purple-800 border-purple-300' },
  { name: 'Web Development', color: 'bg-yellow-200 text-yellow-800 border-yellow-300' },
  { name: 'Database Systems', color: 'bg-red-200 text-red-800 border-red-300' },
  { name: 'Operating Systems', color: 'bg-indigo-200 text-indigo-800 border-indigo-300' },
  { name: 'Linear Algebra', color: 'bg-pink-200 text-pink-800 border-pink-300' },
  { name: 'Calculus II', color: 'bg-orange-200 text-orange-800 border-orange-300' },
  { name: 'Physics I', color: 'bg-cyan-200 text-cyan-800 border-cyan-300' },
];

const faculties = ['Dr. Smith', 'Prof. Jones', 'Dr. Lee', 'Prof. Davis', 'Dr. Patel'];
const rooms = ['A101', 'B202', 'C303', 'Lab-1', 'Lab-2'];
const days: Day[] = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'];

export const mockTimetable: TimetableEntry[] = [
  {
    id: '1',
    dayOfWeek: 'Monday',
    startTime: '09:00',
    endTime: '11:00',
    subject: 'Intro to AI',
    faculty: 'Dr. Smith',
    room: 'A101',
    classId: 'CS301',
    color: subjects[0].color,
  },
  {
    id: '2',
    dayOfWeek: 'Monday',
    startTime: '11:00',
    endTime: '12:00',
    subject: 'Data Structures',
    faculty: 'Prof. Jones',
    room: 'B202',
    classId: 'CS201',
    color: subjects[1].color,
  },
  {
    id: '3',
    dayOfWeek: 'Monday',
    startTime: '14:00',
    endTime: '16:00',
    subject: 'Web Development',
    faculty: 'Dr. Lee',
    room: 'Lab-1',
    classId: 'CS405',
    color: subjects[3].color,
  },
  {
    id: '4',
    dayOfWeek: 'Tuesday',
    startTime: '10:00',
    endTime: '12:00',
    subject: 'Algorithms',
    faculty: 'Dr. Patel',
    room: 'C303',
    classId: 'CS302',
    color: subjects[2].color,
  },
  {
    id: '5',
    dayOfWeek: 'Tuesday',
    startTime: '13:00',
    endTime: '15:00',
    subject: 'Database Systems',
    faculty: 'Prof. Jones',
    room: 'Lab-2',
    classId: 'CS305',
    color: subjects[4].color,
  },
  {
    id: '6',
    dayOfWeek: 'Wednesday',
    startTime: '09:00',
    endTime: '10:00',
    subject: 'Data Structures',
    faculty: 'Prof. Jones',
    room: 'B202',
    classId: 'CS201',
    color: subjects[1].color,
  },
  {
    id: '7',
    dayOfWeek: 'Wednesday',
    startTime: '10:00',
    endTime: '12:00',
    subject: 'Operating Systems',
    faculty: 'Dr. Smith',
    room: 'A101',
    classId: 'CS401',
    color: subjects[5].color,
  },
  {
    id: '8',
    dayOfWeek: 'Wednesday',
    startTime: '15:00',
    endTime: '17:00',
    subject: 'Club Activity',
    faculty: 'N/A',
    room: 'Auditorium',
    classId: 'EXTRA',
    color: 'bg-gray-200 text-gray-800 border-gray-300',
  },
   {
    id: '9',
    dayOfWeek: 'Thursday',
    startTime: '11:00',
    endTime: '13:00',
    subject: 'Calculus II',
    faculty: 'Dr. Evans',
    room: 'D401',
    classId: 'MA202',
    color: subjects[7].color,
  },
  {
    id: '10',
    dayOfWeek: 'Thursday',
    startTime: '14:00',
    endTime: '16:00',
    subject: 'Physics I',
    faculty: 'Dr. Green',
    room: 'PHY-Lab',
    classId: 'PHY101',
    color: subjects[8].color,
  },
  {
    id: '11',
    dayOfWeek: 'Friday',
    startTime: '09:00',
    endTime: '11:00',
    subject: 'Algorithms',
    faculty: 'Dr. Patel',
    room: 'C303',
    classId: 'CS302',
    color: subjects[2].color,
  },
  {
    id: '12',
    dayOfWeek: 'Friday',
    startTime: '13:00',
    endTime: '14:00',
    subject: 'Linear Algebra',
    faculty: 'Dr. Evans',
    room: 'D401',
    classId: 'MA203',
    color: subjects[6].color,
  },
];
