
-- Create a table for public profiles
create table profiles (
  id uuid not null references auth.users on delete cascade,
  name text,
  email text,
  role text,
  class text,
  primary key (id)
);
-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security
alter table profiles
  enable row level security;


-- Create a table for homework assignments
create table homework (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  title text not null,
  description text,
  class text,
  "dueDate" date
);
-- Set up Row Level Security (RLS)
alter table homework
  enable row level security;


-- Create a table for teacher attendance/leave
create table "teacherAttendance" (
  id text not null primary key,
  created_at timestamp with time zone not null default now(),
  status text,
  date date,
  name text,
  uid uuid
);
-- Set up Row Level Security (RLS)
alter table "teacherAttendance"
  enable row level security;
